name: cargo-udeps

on:
  push:
    branches:
      - cargo-udeps
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cargo-udeps
      locked: true
    permissions:
      contents: write
    secrets:
      private_key: ${{ secrets.PRIVATE_KEY }}
